[package]
name = "granular-id"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "ID numbers with arbitrary precision"
repository = "https://github.com/cmdjojo/granular-id/"

[dependencies]
num-traits = "0.2.15"
